networks:
  app-network:
    driver: bridge

services:
  db:
    image: postgres
    container_name: postgres
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build: .
    container_name: app
    networks:
      - app-network
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data: